### ISSUE TITLE
Reports on courses that have used discourse?

### ISSUE THREAD

**Issue by cycomachead** [mit-teaching-systems-lab/discourse-edx-lti#15]
Hey,

This looks great! Do you have any reports from past/current courses about how using Discourse went?
We were chatting about the next run of our MOOC and said "I wonder if we could use Discourse...", so I'm pleased to see MIT has already solved the problem, as usual! :)

**Comment by kevinrobinson** [comment]
Hey there @cycomachead!  This is probably isn't exactly what you're looking for, but here's a report on the last course we ran using Discourse: https://tsl.mit.edu/wp-content/uploads/2017/06/DTLL_Review_2017.pdf.  It's education-centric rather than product- or tech-centric so might not have what you're looking for but gives some context.

If you have any questions I'm happy to chat about them over issues or email.

**Comment by kevinrobinson** [comment]
@cycomachead I'll close this now unless there's anything else immediate you need here.  Let me know if there's anything else I can do to help!

**Comment by cycomachead** [comment]
I got swamped on the weekend prepping a edX course, but this looks great! Thanks! We've been using edX for some online CS PD, so I appreciate that side of things.
